import type {
  GetServerSidePropsContext,
  GetServerSidePropsResult,
  NextPage,
} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import BannerCallMe from '../src/components/Banners/BannerCallMe'
import BannerStepping from '../src/components/Banners/BannerStepping'
import BlueBanner from '../src/components/Banners/BlueBanner'
import OrangeBanner from '../src/components/Banners/OrangeBanner'
import PictureBanner from '../src/components/Banners/PictureBanner'
import Header from '../src/components/Header'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Before You Go</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main> */}
      <Header />
      <BannerStepping />

      <BlueBanner />
      <BannerCallMe />
      <OrangeBanner />
      <PictureBanner />
      {/* </main> */}
    </>
  )
}

export default Home
